[project]
name = "eqr-scoping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.11.2",
    "fsspec>=2025.7.0",
    "universal-pathlib>=0.2.6",
]
