version: 2

sources:
  - name: raw_eqr
    tables:
      - name: transactions
        meta:
          dagster:
            asset_key: ["extract_transactions"]
      - name: contracts
        meta:
          dagster:
            asset_key: ["extract_contracts"]
      - name: ident
        meta:
          dagster:
            asset_key: ["extract_ident"]
      - name: indexPub
        meta:
          dagster:
            asset_key: ["extract_indexPub"]
